version: '3.9'
services:
  clickhouse:
    container_name: clickhouse-srv-local
    image: clickhouse/clickhouse-server:23.1.2.9-alpine
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./config:/etc/clickhouse-server/users.d
    environment:
      CLICKHOUSE_USER: 'default'
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: 'default'
    ports:
    - "8123:8123"
    - "9000:9000"